#!/bin/bash

echo "postinst procedures: start"

# BEGIN: PCM part
ldconfig
/etc/init.d/revsw-pcm-config start
/etc/init.d/revsw-pcm-purge start
# END: PCM part

echo "Removing obsolete proxy configuration file /etc/nginx/conf.d/revsw-bp.conf..."
rm -f /etc/nginx/conf.d/revsw-bp.conf
echo "Removing obsolete proxy configuration file /etc/nginx/conf.d/000-catch-all-bp_nginx.conf..."
rm -f /etc/nginx/conf.d/000-catch-all-bp_nginx.conf 
echo "Removing obsolete proxy configuration file /etc/nginx/conf.d/revsw-cache.conf..."
rm -f /etc/nginx/conf.d/revsw-cache.conf
echo "Removing obsolete proxy configuration file /etc/nginx/conf.d/revsw-nginx-status-page.conf..."
rm -f /etc/nginx/conf.d/revsw-nginx-status-page.conf
echo "Removing obsolete proxy configuration file /etc/nginx/conf.d/revsw-json-access-log-nginx.conf ..."
rm -f /etc/nginx/conf.d/revsw-json-access-log-nginx.conf 

echo "Moving new /etc/nginx/nginx.conf.revsw to /etc/nginx/nginx.conf..."
mv /etc/nginx/nginx.conf.revsw /etc/nginx/nginx.conf

if [ -f /opt/revsw-config/apache/GeoLite2-City.dat ]; then
    echo "Move GeoLite2-City.dat in new directory"
    mv /opt/revsw-config/apache/GeoLite2-City.dat /opt/revsw-config/maxmind
fi

if [ -f /opt/revsw-config/apache/GeoLite2-City.mmdb ]; then
    echo "Move GeoLite2-City.mmdb in new directory"
    mv /opt/revsw-config/apache/GeoLite2-City.mmdb /opt/revsw-config/maxmind
fi

echo "postinst procedures: end"
echo "#"
echo "# Please manually run '/opt/revsw-config/bin/pc-apache-config.py -U' if there was a change in proxy template files or schema"
echo "#"


