#!/bin/bash

echo "postinst procedures: start"

# BEGIN: PCM part
ldconfig
/etc/init.d/revsw-pcm-config start
/etc/init.d/revsw-pcm-purge start
# END: PCM part

# BEGIN: proxy config part

echo "START: Updating all domains"
# /opt/revsw-config/bin/pc-apache-config.py -U
echo "DONE: Updating all domains"

# END: proxy config part

echo "postinst procedures: end"
