#!/bin/bash

status=0

test_files=$(find test*.py)
for t_file in $test_files
    do
    echo "coverage run -t $t_file"
    coverage run $t_file
    status_1=$?
    if [ $status_1 -ne 0 ]
    then
        status=1
    fi
    done
coverage report
exit $status
